routes/web.php
Route::get('/language/{lang?}', ['as' => 'front.setLanguage', 'uses' => 'HomeController@setLanguage' ]);
Route::get('/about', ['as' => 'front.about', 'uses' => 'PageController@about' ]);
Route::get('/faq', ['as' => 'front.faq', 'uses' => 'PageController@faq' ]);
Route::get('/students', ['as' => 'front.students', 'uses' => 'PageController@students' ]);
Route::get('/session', ['as' => 'front.session', 'uses' => 'PageController@session' ]);
Route::get('/policies', ['as' => 'front.policies', 'uses' => 'PageController@policies' ]);
Route::get('/tnc', ['as' => 'front.tnc', 'uses' => 'PageController@tnc' ]);
Route::get('/protection-policy', ['as' => 'front.protectionPolicy', 'uses' => 'PageController@protectionPolicy' ]);
Route::get('/school_background', ['as' => 'front.schoolBackground','uses' => 'PageController@schoolBackground' ]);
Route::get('/regis', ['as' => 'front.regis', 'uses' => 'PageController@regis' ]);
Route::get('/checkout', ['as' => 'front.checkout', 'uses' => 'CheckoutController@index' ]);

Route::post('/api/cart', ['as' => 'front.cartContent', 'uses' => 'CartController@store' ]);
Route::post('/api/add-cart', ['as' => 'front.addCart', 'uses' => 'CartController@addCart' ]);
Route::post('/api/update-cart', ['as' => 'front.updateCart', 'uses' => 'CartController@updateCart' ]);
Route::post('/api/remove-cart', ['as' => 'front.removeCart', 'uses' => 'CartController@removeCart' ]);
Route::post('/login-submit', ['as' => 'front.loginSubmit', 'uses' => 'LoginController@store' ]);
Route::post('/logout', ['as' => 'front.logout', 'uses' => 'LoginController@logout' ]);
Route::get('/logout', ['as' => 'front.logoutGet', 'uses' => 'LoginController@logoutGet' ]);
Route::post('/signup', ['as' => 'front.signup', 'uses' => 'LoginController@signup' ]);
Route::post('/signupgoogle', ['as' => 'front.signupgoogle', 'uses' => 'LoginController@signupgoogle' ]);
Route::post('/reset-password', ['as' => 'front.resetPassword', 'uses' => 'LoginController@resetPassword' ]);
Route::post('/check-session', ['as' => 'front.checkSession', 'uses' => 'LoginController@checkSession' ]);
Route::get('/activate/{email}', ['as' => 'front.activate', 'uses' => 'LoginController@activate' ]);

Route::post('/payment-check', ['as' => 'front.paymentSubmit', 'uses' => 'PaymentController@checkPayment' ]);
Route::get('/payment', ['as' => 'front.payment', 'uses' => 'PaymentController@index' ]);

Route::get('payment.notify.doku', 'PaymentController@DokuNotifyController');
Route::post('payment.notify.doku', 'PaymentController@DokuNotifyController');
Route::post('payment.notify.doku.recuring', 'PaymentController@DokuRecuringNotifyController');
Route::get('payment.redirect.doku', 'PaymentController@DokuRedirectController');
Route::post('payment.redirect.doku', 'PaymentController@DokuRedirectController');
Route::get('verify-payment/{payment_code}', ['as' => 'front.updateDoku', 'uses' => 'PaymentController@UpdateDokuController' ]);
Route::post('payment.notify.doku.recuring.update', 'PaymentController@UpdateProcessNotify');

Route::get('/thankyou', ['as' => 'front.thankyou', 'uses' => 'PageController@thankyou' ]);
Route::get('/failed', ['as' => 'front.failed', 'uses' => 'PageController@failed' ]);
Route::get('/account', ['as' => 'front.account', 'uses' => 'AccountController@index' ]);
Route::get('/donation', ['as' => 'front.donation', 'uses' => 'ItemController@donation' ]);
Route::get('/detail/{type?}/{id?}', ['as' => 'front.detail', 'uses' => 'ItemController@detail' ]);
Route::get('/gift', ['as' => 'front.gift', 'uses' => 'ItemController@gift' ]);
Route::get('/search', ['as' => 'front.search', 'uses' => 'PageController@search' ]);


// LOGIN
Route::get('login', ['as' => 'frontend.login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
Route::post('login', [   'as' => 'frontend.login', 'uses' => 'Auth\LoginController@login']);
Route::get('/login/{provider}', [ 'as' => 'frontend.login.social', 'uses' => 'Auth\LoginController@redirectToProvider']);
Route::get('/login/{provider}/callback', [ 'as' => 'frontend.login.social.callback', 'uses' => 'Auth\LoginController@handleProviderCallback']);

// REGISTER 
Route::get('register', ['as' => 'frontend.register', 'uses' => 'Auth\RegisterController@showRegistrationForm' ]);
Route::post('register', [   'as' => '', 'uses' => 'Auth\RegisterController@register']);

// PASSWORD RESET
Route::post('password/email', [ 'as' => 'frontend.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset', ['as' => 'frontend.password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/reset', ['as' => '', 'uses' => 'Auth\ResetPasswordController@reset']);
Route::get('password/reset/{token}', ['as' => 'frontend.password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

Route::post('password/forgot', [ 'as' => 'frontend.password.forgot', 'uses' => 'LoginController@forgotPassword']);
Route::get('test', ['as' => 'test', 'uses' => 'PaymentController@test']);

// DASHBOARD
Route::middleware(['auth.customer'])->group(function () {
    Route::post('logout', [ 'as' => 'frontend.logout', 'uses' => 'Auth\LoginController@logout' ]);
    Route::get('dashboard/transactions', ['as' => 'frontend.dashboard.transaction', 'uses' => 'TransactionController@index']);
    Route::get('dashboard/customer', ['as' => 'frontend.dashboard.student', 'uses' => 'StudentController@index']);
    Route::get('dashboard/profile', ['as' => 'frontend.dashboard.profile', 'uses' => 'ProfileController@edit']);
    Route::put('dashboard/profile', ['as' => 'frontend.dashboard.profile.update', 'uses' => 'ProfileController@update']);
});

/*-------------------------*/
/*     BACKEND ROUTES      */
/*-------------------------*/

Route::prefix('admin')->namespace('Admin')->group(function () {
    // LOGIN
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
    Route::post('login', [   'as' => '', 'uses' => 'Auth\LoginController@login']);

    // PASSWORD RESET
    Route::post('password/email', [ 'as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => '', 'uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

    Route::middleware(['auth'])->group(function () {
        Route::post('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout' ]);
        Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index' ]);
        Route::get('profile', [ 'as' => 'admin.profile.index', 'uses' => 'ProfileController@edit']);
        Route::put('profile', [ 'as' => 'admin.profile.update', 'uses' => 'ProfileController@update']);

        // USER
        Route::get('user/data', [ 'as' => 'admin.user.data', 'uses' => 'UserController@data']);
        Route::resource('user', 'UserController', ['as' => 'admin']);

        // PERMISSION
        Route::get('permission/data', [ 'as' => 'admin.permission.data', 'uses' => 'PermissionController@data']);
        Route::resource('permission', 'PermissionController', ['as' => 'admin']);

        // ROLE
        Route::get('role/data', [ 'as' => 'admin.role.data', 'uses' => 'RoleController@data']);
        Route::resource('role', 'RoleController', ['as' => 'admin']);

        // STUDENT
        Route::get('student/data', [ 'as' => 'admin.student.data', 'uses' => 'StudentController@data']);
        Route::post('student/upload', [ 'as' => 'admin.student.upload', 'uses' => 'StudentController@upload']);
        Route::get('student/download', [ 'as' => 'admin.student.download', 'uses' => 'StudentController@download']);
        Route::resource('student', 'StudentController', ['as' => 'admin']);

        // SCHOOL
        Route::get('school/data', [ 'as' => 'admin.school.data', 'uses' => 'SchoolController@data']);
        Route::resource('school', 'SchoolController', ['as' => 'admin']);

        //setting
        Route::get('setting/data', [ 'as' => 'admin.setting.data', 'uses' => 'SettingController@data']);
        Route::resource('setting', 'SettingController', ['as' => 'admin']);
        
        // ITEM
        Route::get('item/data', [ 'as' => 'admin.item.data', 'uses' => 'ItemController@data']);
        Route::resource('item', 'ItemController', ['as' => 'admin']);

        // PRICE LIST
        Route::get('pricelist/data', [ 'as' => 'admin.pricelist.data', 'uses' => 'PriceListController@data']);
        Route::get('pricelist-line/{pricelist_id?}', [ 'as' => 'admin.pricelistline.pricelist', 'uses' => 'PriceListLineController@getPriceListLineByPricelistId']);
        Route::resource('pricelist', 'PriceListController', ['as' => 'admin']);

        // CUSTOMER
        Route::get('customer/data', [ 'as' => 'admin.customer.data', 'uses' => 'CustomerController@data']);
        Route::resource('customer', 'CustomerController', ['as' => 'admin']);

        // TRANSACTION
        Route::get('transaction/data', [ 'as' => 'admin.transaction.data', 'uses' => 'TransactionController@data']);
        Route::get('transaction', [ 'as' => 'admin.transaction.index', 'uses' => 'TransactionController@index']);
        Route::get('transaction/print/{transaction}', [ 'as' => 'admin.transaction.print', 'uses' => 'TransactionController@printPage']);
        Route::get('transaction/{transaction}', [ 'as' => 'admin.transaction.show', 'uses' => 'TransactionController@show']);
        
        // COORPORATE
        Route::get('coorporate', ['as' => 'admin.coorporate.index', 'uses' => 'CoorporateController@index']);
        Route::get('coorporate/data', [ 'as' => 'admin.coorporate.data', 'uses' => 'CoorporateController@data']);

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Item;
use App\Models\ItemType;
use App\Models\PriceList;
use Yajra\Datatables\Datatables;
use Intervention\Image\ImageManagerStatic as Image;
use DB;
use Validator;
use Auth;
use File;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.item.index');
    }

    /**
     * Get data items.
     *
     * @return \Illuminate\Http\Response
     */
    public function data(Request $request)
    {
        DB::statement(DB::raw('set @rownum=0'));
        $users = DB::table('items')
                ->select([
                    DB::raw('@rownum := @rownum + 1 AS rownum'),
                    'items.*'
                ]);

        $datatables = Datatables::of($users)
            ->addColumn('action', function ($data) {
                $act = '<a href="'. route("admin.item.edit", ['Item' => $data->id]) .'"><i class="icon icon-pencil"></i></a>';
                $act .= ' <a><i data-id="'. $data->id .'" class="delete icon-trash"></i></a>';

                return $act;
            })
            ->removeColumn('id')
            ->rawColumns(['action']);

        if ($keyword = $request->get('search')['value']) {
            $datatables->filterColumn('rownum', function($query, $keyword) {
                    $sql = '@rownum + 1 like ?';
                    $query->whereRaw($sql, ["%{$keyword}%"]);
            });
        }

        return $datatables->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item_types = ItemType::pluck('name', 'id');
        $price_lists = PriceList::select('start_year', 'end_year', 'id')->where('start_year', '>=', date('Y'))->get();

        return view('backend.item.form', compact('item_types', 'price_lists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'code' => 'required|unique:items',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }

        try {
            $data = new Item;
            $data->name = $request->name;
            $data->code = $request->code;
            $data->is_active = ($request->is_active == 1) ? 1 : 0;
            $data->description_en = $request->description_en;
            $data->description_id = $request->description_id;
            $data->price = $request->price;
            $data->item_type_id = $request->item_type_id;
            $data->price_list_id = $request->price_list_id;
            $data->created_by = Auth::id();
            if($request->hasFile('picture') && $request->file('picture')->isValid()){
                $file = $request->file('picture');
                $fileName = 'item-'. str_slug($request->name, '-') . '-' . date('YmdHis') . '.' . $file->getClientOriginalExtension();

                $thumbnailPath = public_path('uploads/items/200_200_' . $fileName);
                Image::make($file->getRealPath())->fit(200, 200)->save($thumbnailPath);

                $originalPath = public_path('uploads/items/' . $fileName);
                Image::make($file->getRealPath())->save($originalPath);

                $data->picture = $fileName;
            }

            $data->save();

            return redirect()->route('admin.item.index')->with('status', 'Data saved successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->withInput()->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Item::where('id', $id)->firstOrFail();
        $item_types = ItemType::pluck('name', 'id');
        $price_lists = PriceList::select('start_year', 'end_year', 'id')->where('id', $data->price_list_id)->Orwhere('start_year', '>=', date('Y'))->get();

        return view('backend.item.form', compact('data', 'item_types', 'price_lists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'code' => 'required|unique:items,code,' . $id,
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }

        try {
            $data = Item::where('id', $id)->firstOrFail();
            $data->name = $request->name;
            $data->code = $request->code;
            $data->is_active = ($request->is_active == 1) ? 1 : 0;
            $data->description_en = $request->description_en;
            $data->description_id = $request->description_id;
            $data->price = $request->price;
            $data->item_type_id = $request->item_type_id;
            $data->price_list_id = $request->price_list_id;
            if ($request->hasFile('picture') && $request->file('picture')->isValid()){
                $oldPhotoPath = public_path('uploads/items/' . $data->picture);
                $oldThumbnailPhotoPath = public_path('uploads/items/200_200_' . $data->picture);
                
                $file = $request->file('picture');
                $fileName = 'item-'. str_slug($request->name, '-') . '-' . date('YmdHis') . '.' . $file->getClientOriginalExtension();
    
                $thumbnailPath = public_path('uploads/items/200_200_' . $fileName);
                Image::make($file->getRealPath())->fit(200, 200)->save($thumbnailPath);
    
                $originalPath = public_path('uploads/items/' . $fileName);
                Image::make($file->getRealPath())->save($originalPath);
    
                $data->picture = $fileName;
            }
    
            $data->save();

            if (isset($oldPhotoPath) && File::exists($oldPhotoPath)) {
                File::delete($oldPhotoPath);
                File::delete($oldThumbnailPhotoPath);
            }

            return redirect()->route('admin.item.index')->with('status', 'Data updated successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->withInput()->withErrors(['Failed to update data. ' . $e->getMessage() ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Item::where('id', $id)->firstOrFail();
            $photoPath = public_path('uploads/items/' . $data->picture);
            $thumbnailPhotoPath = public_path('uploads/items/200_200_' . $data->picture);

            if ($data->delete()) {
                if (File::exists($photoPath)) {
                    File::delete($photoPath);
                    File::delete($thumbnailPhotoPath);
                }
            }

            return response()->json([]);
        } catch (\Exception $e) {
            return response()->json([], $e->getStatusCode());
        }
    }
}

resources/views/backend/item/form.blade.php
@extends('backend.layouts.app')

@section('breadcrumb')
<div class="page-title">
    <div class="page-breadcrumb">
        <h3 class="breadcrumb-header">{{ isset($data) ? 'Update Item' : 'Create New Item' }}</h3>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.dashboard') }}">Home</a></li>
            <li><a href="{{ route('admin.item.index') }}">Item</a></li>
            <li class="active">{{ isset($data) ? 'Update Row' : 'Create New Row' }}</li>
        </ol>
    </div>
</div>
@endsection

@section('content')
<div id="main-wrapper">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-white">
        <div class="panel-body">
          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          @endif
          <form role="form" method="POST" enctype="multipart/form-data" action="{{ isset($data) ? route('admin.item.update', ['item' => $data->id]) : route('admin.item.store') }}">
            @if(isset($data))
              <input name="_method" type="hidden" value="PUT">
            @endif
            {{ csrf_field() }}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="name">Name</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter Item Name" value="{{ isset($data) ? $data->name : old('name') }}">
                </div>
                <div class="form-group">
                  <label for="name">Name (ID)</label>
                  <input type="text" name="name_id" class="form-control" id="name_id" placeholder="Enter Item Name (ID)" value="{{ isset($data) ? $data->name_id : old('name_id') }}">
                </div>
                <div class="form-group">
                  <label for="code">Code</label>
                  <input type="text" name="code" class="form-control" id="code" placeholder="Enter Item Code" value="{{ isset($data) ? $data->code : old('code') }}">
                </div>
                <div class="form-group">
                  <label for="is_active">Is Active</label>
                  <input type="checkbox" {{ ((isset($data) && $data->is_active == 1) or old('is_active') == 1) ? 'checked' : '' }} name="is_active" class="form-control" id="is_active" value="1" />
                </div>
                <div class="form-group">
                  <label for="picture">Picture</label>
                  @if(isset($data) && !empty($data->picture))
                  <div class="input-group">
                    <a href="{{ asset('uploads/items/'. $data->picture) }}">
                      <img class="thumbnail" src="{{ asset('uploads/items/'.$data->picture) }}" style="height: 200px; width: 200px;" />
                    </a>
                  </div>
                  @endif
                  <input name="picture" class="form-control" id="file" type="file" />
                </div>
                <div class="form-group">
                  <label for="item_type_id">Item Type</label>
                  <select name="item_type_id" id="item_type_id" class="form-control">
                    @foreach($item_types as $k => $v)
                      <option {{ ((isset($data) && $data->item_type_id === $k) or old("item_type_id") === $k) ? 'selected' : '' }} value="{{ $k }}">{{ $v }}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group" id="donation">
                  <label for="price_list_id">Price List</label>
                  <select name="price_list_id" class="price_list_id form-control">
                    <option value=''>- Select Price List -</option>
                    @foreach($price_lists as $k => $v)
                      <option {{ ((isset($data) && $data->price_list_id === $v->id) or old("price_list_id") === $v->id) ? 'selected' : '' }} value="{{ $v->id }}">{{ $v->start_year . ' - ' . $v->end_year }}</option>
                    @endforeach
                  </select>
                  <div id="table-donation">
                    @if (isset($data->price_list) && !empty($data->price_list->lines))
                      <table class="table table-bordered" style="margin-top: 10px;">
                        <tr>
                          <th width="10">No.</th>
                          <th>School</th>
                          <th>Price</th>
                        </tr>
                        @foreach($data->price_list->lines as $k => $v)
                        <tr>
                          <td>{{ $k + 1 }}</td>
                          <td>{{ $v->school->name }}</td>
                          <td>Rp. {{ $v->price }}</td>
                        </tr>
                        @endforeach
                      </table>
                    @endif
                  </div>
                </div>
                <div class="form-group" id="item">
                  <label for="price">Price</label>
                  <input type="number" name="price" class="form-control price" id="price" placeholder="Enter Price" value="{{ isset($data) ? $data->price : old('price') }}">
                </div>
                <div class="form-group">
                  <label for="description_en">Description (EN)</label>
                  <textarea name="description_en" class="description_en">{{ isset($data) ? $data->description_en : old('description_en') }}</textarea>
                </div>
                <div class="form-group">
                  <label for="description_id">Description (ID)</label>
                  <textarea name="description_id" class="description_id">{{ isset($data) ? $data->description_id : old('description_id') }}</textarea>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <a href="{{ route('admin.item.index') }}" class="btn btn-default">&laquo; Back</a>
                <button type="submit" class="pull-right btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('styles')
<link href="{{ asset('assets/plugins/summernote-master/summernote.css') }}" rel="stylesheet" type="text/css"/>
@endsection

@section('scripts')
<script src="{{ asset('assets/plugins/summernote-master/summernote.min.js') }}"></script>
<script>
  $(document).ready(function() {
    var donationValue = 1;
    var itemValue = 2;
    var tablePriceList = $("#table-donation");
    var itemTypeSelector = $("#item_type_id");
    var donationSelector = $("#donation");
    var priceListSelector = $(".price_list_id");
    var priceSelector = $(".price");
    var itemSelector = $("#item");
    var itemType = itemTypeSelector.val();
    // If donation
    if (itemType == donationValue) {
      donationSelector.show();
      itemSelector.hide();
      priceSelector.val('');
    } else {
      donationSelector.hide();
      priceListSelector.val('');
      itemSelector.show();
    }

    itemTypeSelector.on('change', function() {
      if ($(this).val() == donationValue) {
        donationSelector.show();
        itemSelector.hide();
      } else {
        tablePriceList.html('');
        donationSelector.hide();
        itemSelector.show();
      }

      priceListSelector.val('');
      priceSelector.val('');
    });

    priceListSelector.on('change', function() {
      var pricelistId = $(this).val();
      $.ajax({
        url: "{{ route('admin.pricelistline.pricelist') }}/" + pricelistId,
        method: 'GET',
        success: function (data) {
          var dataCount = data.length;
          var html = '<table style="margin-top:10px;" class="table table-bordered">';
          html += '<tr>';
          html += '<th>No.</th>';
          html += '<th>School</th>';
          html += '<th>Price</th>';
          html += '</tr>';
          for (var x = 0; x < dataCount; x += 1) {
            html += '<tr>';
            html += '<td width="10">' + (x + 1) + '</td>';
            html += '<td>' + data[x].school.name + '</td>';
            html += '<td>Rp. ' + data[x].price + '</td>';
            html += '</tr>';
          }
          html += '</table>';

          tablePriceList.html(html);
        }
      });
    });
    
    $('.description_id').summernote({
      height: 200
    });
    $('.description_en').summernote({
      height: 200
    });
  });
</script>
@endsection

resources/views/backend/item/index.blade.php
@extends('backend.layouts.app')

@section('breadcrumb')
<div class="page-title">
    <div class="page-breadcrumb">
        <h3 class="breadcrumb-header">Items</h3>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.dashboard') }}">Home</a></li>
            <li class="active">Item</li>
        </ol>
    </div>
</div>
@endsection

@section('content')
<div id="main-wrapper">
  <div class="row">
      <div class="col-md-12">
          <div class="panel panel-white">
              <div class="panel-heading">
                  <a class="btn btn-success m-b-sm" href="{{ route('admin.item.create') }}">Add new row</a>
              </div>
              <div class="panel-body">
                  <div class="table-responsive">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                      <table id="data-table" class="display table dataTable" style="width: 100%; cellspacing: 0;">
                        <thead>
                          <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tfoot>
                          <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Action</th>
                          </tr>
                        </tfoot>
                      </table>  
                  </div>
              </div>
          </div>
      </div>
  </div><!-- Row -->
</div><!-- Main Wrapper -->
@endsection

@section('styles')
<link href="{{ asset('assets/plugins/datatables/css/jquery.datatables.min.css') }}" rel="stylesheet" type="text/css"/>	
<link href="{{ asset('assets/plugins/datatables/css/jquery.datatables_themeroller.css') }}" rel="stylesheet" type="text/css"/>	
<link rel="stylesheet" href="{{ asset('assets/plugins/bootstrap-sweetalert/dist/sweetalert.css') }}">
@endsection

@section('scripts')
<script src="{{ asset('assets/plugins/datatables/js/jquery.datatables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-sweetalert/dist/sweetalert.js') }}"></script>
<script>
$(document).ready(function() {
    function init() {
        let table = $('#data-table').DataTable({
          processing: true,
          serverSide: true,
          responsive: true,
          destroy: true,
          ajax: '{!! route('admin.item.data') !!}',
          columns: [
            { data: 'rownum', name: 'rownum'},
            { data: 'name', name: 'name' },
            { data: 'code', name: 'code' },
            { data: "action", orderable: false, searchable: false, class: "text-left" }
          ],
          fnDrawCallback: () => {
            $(".delete").on('click', onDelete);
          },
          initComplete: () => {
            $(".delete").on('click', onDelete);
          }
        });
    }

    init();

    //---------- SWEET ALERT ------------//
    function onDelete(data) {
        data.preventDefault();
        return swal({
          title: "Are you sure?",
          text: "Your will not be able to recover this data!",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-danger",
          confirmButtonText: "Yes, delete it!",
          closeOnConfirm: false
        }, () => {
          let url = '{{ route("admin.item.destroy", [ "item" => ":id"]) }}';
          url = url.replace(':id', $(this).data('id'));
          $.ajax({
            url: url,
            type: 'json',
            data: '_token={{ csrf_token() }}',
            method: 'DELETE',
            error: () => {
              swal("Error!", "Failed to delete data item. Please try again later.", "error");
            },
            success: () => {
              swal("Deleted!", "Data item has been deleted.", "success");
              init();
            }
          });
        });
    }
});
</script>
@endsection