routes/web.php
Route::get('/payment', ['as' => 'front.payment', 'uses' => 'PaymentController@index' ]);

Route::get('payment.notify.doku', 'PaymentController@DokuNotifyController');
Route::post('payment.notify.doku', 'PaymentController@DokuNotifyController');
Route::post('payment.notify.doku.recuring', 'PaymentController@DokuRecuringNotifyController');
Route::get('payment.redirect.doku', 'PaymentController@DokuRedirectController');
Route::post('payment.redirect.doku', 'PaymentController@DokuRedirectController');
Route::get('verify-payment/{payment_code}', ['as' => 'front.updateDoku', 'uses' => 'PaymentController@UpdateDokuController' ]);
Route::post('payment.notify.doku.recuring.update', 'PaymentController@UpdateProcessNotify');

Route::get('/thankyou', ['as' => 'front.thankyou', 'uses' => 'PageController@thankyou' ]);
Route::get('/failed', ['as' => 'front.failed', 'uses' => 'PageController@failed' ]);
Route::get('/account', ['as' => 'front.account', 'uses' => 'AccountController@index' ]);
Route::get('/donation', ['as' => 'front.donation', 'uses' => 'ItemController@donation' ]);
Route::get('/detail/{type?}/{id?}', ['as' => 'front.detail', 'uses' => 'ItemController@detail' ]);
Route::get('/gift', ['as' => 'front.gift', 'uses' => 'ItemController@gift' ]);
Route::get('/search', ['as' => 'front.search', 'uses' => 'PageController@search' ]);


// LOGIN
Route::get('login', ['as' => 'frontend.login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
Route::post('login', [   'as' => 'frontend.login', 'uses' => 'Auth\LoginController@login']);
Route::get('/login/{provider}', [ 'as' => 'frontend.login.social', 'uses' => 'Auth\LoginController@redirectToProvider']);
Route::get('/login/{provider}/callback', [ 'as' => 'frontend.login.social.callback', 'uses' => 'Auth\LoginController@handleProviderCallback']);

// REGISTER 
Route::get('register', ['as' => 'frontend.register', 'uses' => 'Auth\RegisterController@showRegistrationForm' ]);
Route::post('register', [   'as' => '', 'uses' => 'Auth\RegisterController@register']);

// PASSWORD RESET
Route::post('password/email', [ 'as' => 'frontend.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset', ['as' => 'frontend.password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/reset', ['as' => '', 'uses' => 'Auth\ResetPasswordController@reset']);
Route::get('password/reset/{token}', ['as' => 'frontend.password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

Route::post('password/forgot', [ 'as' => 'frontend.password.forgot', 'uses' => 'LoginController@forgotPassword']);
Route::get('test', ['as' => 'test', 'uses' => 'PaymentController@test']);

// DASHBOARD
Route::middleware(['auth.customer'])->group(function () {
    Route::post('logout', [ 'as' => 'frontend.logout', 'uses' => 'Auth\LoginController@logout' ]);
    Route::get('dashboard/transactions', ['as' => 'frontend.dashboard.transaction', 'uses' => 'TransactionController@index']);
    Route::get('dashboard/customer', ['as' => 'frontend.dashboard.student', 'uses' => 'StudentController@index']);
    Route::get('dashboard/profile', ['as' => 'frontend.dashboard.profile', 'uses' => 'ProfileController@edit']);
    Route::put('dashboard/profile', ['as' => 'frontend.dashboard.profile.update', 'uses' => 'ProfileController@update']);
});

/*-------------------------*/
/*     BACKEND ROUTES      */
/*-------------------------*/

Route::prefix('admin')->namespace('Admin')->group(function () {
    // LOGIN
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
    Route::post('login', [   'as' => '', 'uses' => 'Auth\LoginController@login']);

    // PASSWORD RESET
    Route::post('password/email', [ 'as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => '', 'uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

    Route::middleware(['auth'])->group(function () {
        Route::post('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout' ]);
        Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index' ]);
        Route::get('profile', [ 'as' => 'admin.profile.index', 'uses' => 'ProfileController@edit']);
        Route::put('profile', [ 'as' => 'admin.profile.update', 'uses' => 'ProfileController@update']);

        // USER
        Route::get('user/data', [ 'as' => 'admin.user.data', 'uses' => 'UserController@data']);
        Route::resource('user', 'UserController', ['as' => 'admin']);

        // PERMISSION
        Route::get('permission/data', [ 'as' => 'admin.permission.data', 'uses' => 'PermissionController@data']);
        Route::resource('permission', 'PermissionController', ['as' => 'admin']);

        // ROLE
        Route::get('role/data', [ 'as' => 'admin.role.data', 'uses' => 'RoleController@data']);
        Route::resource('role', 'RoleController', ['as' => 'admin']);

        // STUDENT
        Route::get('student/data', [ 'as' => 'admin.student.data', 'uses' => 'StudentController@data']);
        Route::post('student/upload', [ 'as' => 'admin.student.upload', 'uses' => 'StudentController@upload']);
        Route::get('student/download', [ 'as' => 'admin.student.download', 'uses' => 'StudentController@download']);
        Route::resource('student', 'StudentController', ['as' => 'admin']);

        // SCHOOL
        Route::get('school/data', [ 'as' => 'admin.school.data', 'uses' => 'SchoolController@data']);
        Route::resource('school', 'SchoolController', ['as' => 'admin']);

        //setting
        Route::get('setting/data', [ 'as' => 'admin.setting.data', 'uses' => 'SettingController@data']);
        Route::resource('setting', 'SettingController', ['as' => 'admin']);
        
        // ITEM
        Route::get('item/data', [ 'as' => 'admin.item.data', 'uses' => 'ItemController@data']);
        Route::resource('item', 'ItemController', ['as' => 'admin']);

        // PRICE LIST
        Route::get('pricelist/data', [ 'as' => 'admin.pricelist.data', 'uses' => 'PriceListController@data']);
        Route::get('pricelist-line/{pricelist_id?}', [ 'as' => 'admin.pricelistline.pricelist', 'uses' => 'PriceListLineController@getPriceListLineByPricelistId']);
        Route::resource('pricelist', 'PriceListController', ['as' => 'admin']);

        // CUSTOMER
        Route::get('customer/data', [ 'as' => 'admin.customer.data', 'uses' => 'CustomerController@data']);
        Route::resource('customer', 'CustomerController', ['as' => 'admin']);

        // TRANSACTION
        Route::get('transaction/data', [ 'as' => 'admin.transaction.data', 'uses' => 'TransactionController@data']);
        Route::get('transaction', [ 'as' => 'admin.transaction.index', 'uses' => 'TransactionController@index']);
        Route::get('transaction/print/{transaction}', [ 'as' => 'admin.transaction.print', 'uses' => 'TransactionController@printPage']);
        Route::get('transaction/{transaction}', [ 'as' => 'admin.transaction.show', 'uses' => 'TransactionController@show']);
        
        // COORPORATE
        Route::get('coorporate', ['as' => 'admin.coorporate.index', 'uses' => 'CoorporateController@index']);
        Route::get('coorporate/data', [ 'as' => 'admin.coorporate.data', 'uses' => 'CoorporateController@data']);
        Route::get('coorporate/datastudent/{id}', [ 'as' => 'admin.coorporate.datastudent', 'uses' => 'CoorporateController@dataStudent']);
        Route::get('coorporate/datapayment', [ 'as' => 'admin.coorporate.datapayment', 'uses' => 'CoorporateController@dataPayment']);
        Route::get('coorporate/edit/{id}', [ 'as' => 'admin.coorporate.edit', 'uses' => 'CoorporateController@edit']);
        Route::get('coorporate/payment/{id}', [ 'as' => 'admin.coorporate.payment', 'uses' => 'CoorporateController@payment']);
        Route::post('coorporate/updatedetailpayment', ['as' => 'admin.coorporate.updatedetailpayment', 'uses' => 'CoorporateController@updateDetailPayment']);
        Route::post('coorporate/deletepayment', ['as' => 'admin.coorporate.deletedetailpayment', 'uses' => 'CoorporateController@deleteDetailPayment']);
        Route::post('coorporate/store', ['as' => 'admin.coorporate.store', 'uses' => 'CoorporateController@store']);
        Route::post('coorporate/upload', [ 'as' => 'admin.coorporate.upload', 'uses' => 'CoorporateController@upload']);
        Route::post('coorporate/uploadpayment', [ 'as' => 'admin.coorporate.uploadpayment', 'uses' => 'CoorporateController@uploadPayment']);
        Route::post('coorporate/loadpayment', ['as' => 'admin.coorporate.loadpayment', 'uses' => 'CoorporateController@loadPayment']);
        Route::get('coorporate/downloadpayment/{id}', [ 'as' => 'admin.coorporate.downloadpayment', 'uses' => 'CoorporateController@downloadpayment']);
        Route::get('coorporate/downloadstudent/{id}', [ 'as' => 'admin.coorporate.downloadstudent', 'uses' => 'CoorporateController@downloadstudent']);
        // Route::resource('coorporate', 'CoorporateController', ['as' => 'admin']);
    });
});


/*--------------------------*/ 
/*     FRONTEND ROUTES      */
/*--------------------------*/

// LOGIN
Route::get('login', ['as' => 'frontend.login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
Route::post('login', [   'as' => '', 'uses' => 'Auth\LoginController@login']);

// REGISTER
Route::get('register', ['as' => 'frontend.register', 'uses' => 'Auth\RegisterController@showRegistrationForm' ]);
Route::post('register', [   'as' => '', 'uses' => 'Auth\RegisterController@register']);

// PASSWORD RESET

app/Models/Role.php
<?php
namespace App\Models;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
  //
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Permission;
use Yajra\Datatables\Datatables;
use Carbon\Carbon;
use DB;
use Validator;

class RoleController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      return view('backend.role.index');
  }

  /**
   * Get data roles.
   *
   * @return \Illuminate\Http\Response
   */
  public function data(Request $request)
  {
      DB::statement(DB::raw('set @rownum=0'));
      $users = DB::table('roles')
              ->select([
                DB::raw('@rownum := @rownum + 1 AS rownum'),
                'roles.*'
              ]);

      $datatables = Datatables::of($users)
        ->addColumn('action', function ($data) {
            $act = '<a href="'. route("admin.role.edit", ['Role' => $data->id]) .'"><i class="icon-pencil"></i></a>';
            $act .= ' <a><i data-id="'. $data->id .'" class="delete icon-trash"></i></a>';

            return $act;
        })
        ->removeColumn('id')
        ->rawColumns(['action']);

      if ($keyword = $request->get('search')['value']) {
          $datatables->filterColumn('rownum', function($query, $keyword) {
                  $sql = '@rownum + 1 like ?';
                  $query->whereRaw($sql, ["%{$keyword}%"]);
          });
      }

      return $datatables->make(true);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      $permissions = Permission::all();
      return view('backend.role.form', compact('permissions'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $validator = Validator::make($request->all(), [
        'name' => 'required',
        'display_name' => 'required',
        'description' => 'required',
        'permissions' => 'required'
      ]);

      if ($validator->fails()) {
          return redirect()->back()->withInput()->withErrors($validator);
      }

      try {
        $data = new Role;
        $data->name = $request->name;
        $data->display_name = $request->display_name;
        $data->description = $request->description;
        $data->save();

        $data->attachPermissions($request->permissions);

        return redirect()->route('admin.role.index')->with('status', 'Data saved successfully!');
      } catch (\Exception $e) {
        return redirect()->back()->withInput()->withErrors([$e->getMessage()]);
      }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      $data = Role::where('id', $id)->firstOrFail();
      $permissions = Permission::all();

      return view('backend.role.form', compact('data', 'permissions'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $validator = Validator::make($request->all(), [
      'name' => 'required',
      'display_name' => 'required',
      'description' => 'required',
      'permissions' => 'required'
    ]);

    if ($validator->fails()) {
        return redirect()->back()->withInput()->withErrors($validator);
    }

    try {
      $data = Role::where('id', $id)->firstOrFail();
      $data->name = $request->name;
      $data->display_name = $request->display_name;
      $data->description = $request->description;
      $data->save();

      $data->perms()->sync([]);
      $data->attachPermissions($request->permissions);

      return redirect()->route('admin.role.index')->with('status', 'Data updated successfully!');
    } catch (\Exception $e) {
      return redirect()->back()->withInput()->withErrors([$e->getMessage()]);
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      try {
        Role::where('id', $id)->firstOrFail()->delete();

        return response()->json([]);
      } catch (\Exception $e) {
        return response()->json([], $e->getStatusCode());
      }
  }
}

resources/views/backend/backend/role/form.blade.php
@extends('backend.layouts.app')

@section('breadcrumb')
<div class="page-title">
    <div class="page-breadcrumb">
        <h3 class="breadcrumb-header">{{ isset($data) ? 'Update Row' : 'Create New Row' }}</h3>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.dashboard') }}">Home</a></li>
            <li><a href="{{ route('admin.role.index') }}">Role</a></li>
            <li class="active">{{ isset($data) ? 'Update Row' : 'Create New Row' }}</li>
        </ol>
    </div>
</div>
@endsection

@section('content')
<div id="main-wrapper">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-white">
        <div class="panel-body">
          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          @endif
          <form role="form" method="POST" enctype="multipart/form-data" action="{{ isset($data) ? route('admin.role.update', ['role' => $data->id]) : route('admin.role.store') }}">
            @if(isset($data))
              <input name="_method" type="hidden" value="PUT">
            @endif
            {{ csrf_field() }}
            <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <div class="form-group">
                  <label for="name">Name</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter Name" value="{{ $data->name or old('name') }}">
                </div>
                <div class="form-group">
                  <label for="display_name">Display Name</label>
                  <input type="text" name="display_name" class="form-control" id="display_name" placeholder="Enter Display Name" value="{{ $data->display_name or old('display_name') }}">
                </div>
                <div class="form-group">
                  <label for="description">Description</label>
                  <input type="text" name="description" class="form-control" id="description" placeholder="Enter Description" value="{{ $data->description or old('description') }}">
                </div>
                <div class="form-group">
                  <label for="permissions">Permissions</label>
                  @foreach($permissions as $val)
                    <br />
                    <input id="{{ $val->name }}" class="minimal" type="checkbox" {!! isset($data) && $data->hasPermission($val->name) ? 'checked="checked"' : '' !!} name="permissions[]" value="{{ $val->id }}" /> <label for="{{ $val->name }}" style="font-weight: normal">{{ $val->display_name }}</label>
                  @endforeach
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <a href="{{ route('admin.role.index') }}" class="btn btn-default">&laquo; Back</a>
                <button type="submit" class="pull-right btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/backend/backend/role/index.blade.php
@extends('backend.layouts.app')

@section('breadcrumb')
<div class="page-title">
    <div class="page-breadcrumb">
        <h3 class="breadcrumb-header">Roles</h3>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.dashboard') }}">Home</a></li>
            <li class="active">Role</li>
        </ol>
    </div>
</div>
@endsection

@section('content')
<div id="main-wrapper">
  <div class="row">
      <div class="col-md-12">
          <div class="panel panel-white">
              <div class="panel-heading">
                  <a class="btn btn-success m-b-sm" href="{{ route('admin.role.create') }}">Add new row</a>
              </div>
              <div class="panel-body">
                  <div class="table-responsive">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                      <table id="data-table" class="display table dataTable" style="width: 100%; cellspacing: 0;">
                        <thead>
                          <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Display Name</th>
                            <th>Description</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tfoot>
                          <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Display Name</th>
                            <th>Description</th>
                            <th>Action</th>
                          </tr>
                        </tfoot>
                      </table>  
                  </div>
              </div>
          </div>
      </div>
  </div><!-- Row -->
</div><!-- Main Wrapper -->
@endsection

@section('styles')
<link href="{{ asset('assets/plugins/datatables/css/jquery.datatables.min.css') }}" rel="stylesheet" type="text/css"/>	
<link href="{{ asset('assets/plugins/datatables/css/jquery.datatables_themeroller.css') }}" rel="stylesheet" type="text/css"/>	
<link rel="stylesheet" href="{{ asset('assets/plugins/bootstrap-sweetalert/dist/sweetalert.css') }}">
@endsection

@section('scripts')
<!-- Sweet Alert -->
<script src="{{ asset('assets/plugins/datatables/js/jquery.datatables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-sweetalert/dist/sweetalert.js') }}"></script>
<script>
$(document).ready(function() {
    function init() {
        let table = $('#data-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            destroy: true,
            ajax: '{!! route('admin.role.data') !!}',
            columns: [
                { data: 'rownum', name: 'rownum'},
                { data: 'name', name: 'name' },
                { data: 'display_name', name: 'display_name' },
                { data: 'description', name: 'description' },
                { data: "action", orderable: false, searchable: false, class: "text-left" }
            ],
            fnDrawCallback: () => {
                $(".delete").on('click', onDelete);
            },
            initComplete: () => {
                $(".delete").on('click', onDelete);
            }
        });
    }

    init();

    //---------- SWEET ALERT ------------//
    function onDelete(data) {
        data.preventDefault();
        return swal({
            title: "Are you sure?",
            text: "Your will not be able to recover this data!",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: false
        }, () => {
            let url = '{{ route("admin.role.destroy", [ "role" => ":id"]) }}';
            url = url.replace(':id', $(this).data('id'));
            $.ajax({
                url: url,
                type: 'json',
                data: '_token={{ csrf_token() }}',
                method: 'DELETE',
                error: () => {
                swal("Error!", "Failed to delete data role. Please try again later.", "error");
                },
                success: () => {
                swal("Deleted!", "Data role has been deleted.", "success");
                init();
                }
            });
    });
    }
});
</script>
@endsection